# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-latest'

steps:

- task: NuGetToolInstaller@0
  displayName: 'Use latest NuGet'

- task: NuGetCommand@2
  displayName: 'NuGet Restore'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '**/*.sln'
    clean: true

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/*.Tests.csproj'

